# List all wprds for which the odd/even letters make another word. The "odd letters" are the 1st, 3rd, 5th, ect, and the 'even letters' are the 2nd, 4th, 6th, ...
# Only words of 5+ letters (for odd) and 6+ letters (for even) should be considered, i.e. the resulting word must be 3+ letters.
# Examples: DERBY (which makes DRY), UNBUNDLED (which makes NUDE)
